// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZlCsSLF8Pq9aOXdM7b-DkvwThpa9OQc',
    appId: '1:81594979734:web:82f633b65d16e37ffff9b7',
    messagingSenderId: '81594979734',
    projectId: 'pifarm-91c37',
    authDomain: 'pifarm-91c37.firebaseapp.com',
    databaseURL: 'https://pifarm-91c37-default-rtdb.firebaseio.com',
    storageBucket: 'pifarm-91c37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOFGVR7C0pyhLac2DtlQQdtFUP0i3Btw',
    appId: '1:81594979734:android:f932eed079f250cafff9b7',
    messagingSenderId: '81594979734',
    projectId: 'pifarm-91c37',
    databaseURL: 'https://pifarm-91c37-default-rtdb.firebaseio.com',
    storageBucket: 'pifarm-91c37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQmhyxvyGtivMMbwkdUFN8PxTRxHbqo0',
    appId: '1:81594979734:ios:87659ae2cf2f26e2fff9b7',
    messagingSenderId: '81594979734',
    projectId: 'pifarm-91c37',
    databaseURL: 'https://pifarm-91c37-default-rtdb.firebaseio.com',
    storageBucket: 'pifarm-91c37.firebasestorage.app',
    iosBundleId: 'com.example.piFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnQmhyxvyGtivMMbwkdUFN8PxTRxHbqo0',
    appId: '1:81594979734:ios:87659ae2cf2f26e2fff9b7',
    messagingSenderId: '81594979734',
    projectId: 'pifarm-91c37',
    databaseURL: 'https://pifarm-91c37-default-rtdb.firebaseio.com',
    storageBucket: 'pifarm-91c37.firebasestorage.app',
    iosBundleId: 'com.example.piFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZlCsSLF8Pq9aOXdM7b-DkvwThpa9OQc',
    appId: '1:81594979734:web:9b43af76f08a7291fff9b7',
    messagingSenderId: '81594979734',
    projectId: 'pifarm-91c37',
    authDomain: 'pifarm-91c37.firebaseapp.com',
    databaseURL: 'https://pifarm-91c37-default-rtdb.firebaseio.com',
    storageBucket: 'pifarm-91c37.firebasestorage.app',
  );
}
